# Model parameter
model_name: 'resnet18'

# environment/computational parameters
seed: 32678456782 # random number generator seed (long integer value)
device: 'cuda' # if you have multiple GPU's, you can use 'cude:4' to specify which GPU to run on, e.g., the 4th
num_workers: 16  # number of CPU cores that load data in parallel. You can set this to the number of logical CPU cores that you have. 

# dataset parameters
basepath: '/mnt/class_data/group4/val/trailcam/'
train_val_split: 0.3
data_frac: 1.0

# training hyperparameters
image_size: [224, 224]
num_epochs: 100 # number of epochs. Each epoch has multiple iterations. In each epoch the model goes over the full dataset once.
batch_size: 128 # number of images that are processed in parallel in every iteration
learning_rate: 0.0001 # hyperparameter to adjust the optimizer's learning rate 
weight_decay: 0 # hyperparameter for regularization