program: mdclassifier/train.py
name: major-sweep
method: grid
metric:
  goal: minimize
  name: loss_val
parameters:
  wandb_project: 
    value: "cv4e-sweep"
  basepath: 
    value: '/mnt/class_data/group4/val/trailcam/'
  train_val_split: 
    value: 0.3
  data_frac: 
    values: [0.5, 1]
  seed: 
    value: 32678456782 # random number generator seed (long integer value)
  device: 
    value: 'cuda' # if you have multiple GPU's, you can use 'cude:4' to specify which GPU to run on, e.g., the 4th
  num_workers: 
    value: 64  # number of CPU cores that load data in parallel. You can set this to the number of logical CPU cores that you have. 
  model_name: 
    value: 'resnet18'
  freezed: 
    value: False
  image_size: 
    value: 224
  num_epochs:
    values: [10, 50, 100]
  batch_size:
    values: [32, 64, 128]
  learning_rate:
    values: [0.00001, 0.0001, 0.001, 0.01]
  weight_decay:
    values: [0, 0.05, 0.01, 0.05, 0.1]
  optimizer:
    values: ["sgd", "adam", "adamw"]
  rotation:
    values: [0, 15, 30, 45]
  horizontal_flip:
    values: [0, 0.25, 0.5]