program: mdclassifier/train.py
name: cv4e-sweep
method: grid
metric:
  goal: minimize
  name: loss_val
parameters:
  wandb_project: 
    value: "cv4e-sweep-jan21-bin-bal"
  basepath: 
    value: '/mnt/class_data/group4/val/trailcam/'
  train_val_split: 
    value: 0.3
  data_frac: 
    value: 1
  seed: 
    values: [32678456782, 10366395667, 46303749199, 13757672088, 57650004417] # random number generator seed (long integer value)
  device: 
    value: 'cuda' # if you have multiple GPU's, you can use 'cude:4' to specify which GPU to run on, e.g., the 4th
  num_workers: 
    value: 32  # number of CPU cores that load data in parallel. You can set this to the number of logical CPU cores that you have. 
  model_name: 
    value: 'resnet18'
  binary:
    value: True
  balanced:
    values: [True, False]
  freezed: 
    value: False
  image_size: 
    value: 224
  num_epochs:
    value: 100
  batch_size:
    value: 256 
  learning_rate:
    values: [0.0001, 0.001]
  weight_decay:
    value: 0
  optimizer:
    values: ["sgd", "adamw"]
  rotation:
    value: 0
  horizontal_flip:
    value: 0